<div class="copyrighthome"><div class="social"><a target="_blank" href='https://www.facebook.com/mokacafeegypt'><img src="images/icons/facebook.png" class="socialIcon" alt=""></a><a href='#'><img src="images/icons/Twitter.png" class="socialIcon" alt=""></a><a href='#'><img src="images/icons/email.png" class="socialIcon" alt=""></a></div>
جميع الحقوق محفوظة © 2014  <a href="http://makkcg.com" target="_blank">موكا كافيه بواسطة م. محمد خليفة</a>
</div>
<!--------------end of copyright and footer ---------->
<!--<div class="copyrighthome">
All Rights Reserved. Copyright © 2014 <a href="http://makkcg.com" target="_blank">Moka Cafe by Eng. Mohammed Khalifa</a>
</div>-->
