<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>موكا كافيه - Moka Cafe</title>
<script type="text/javascript" src="./js/jquery-1.9.1.js"></script>
<script type="text/javascript" src="./js/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="css/index.css" />
<link rel="stylesheet" type="text/css" href="css/homemenu.css" />
<link rel="stylesheet" type="text/css" href="css/Regform_style.css"/>
<!-- Load date picker https://code.google.com/p/datepickr/
<script type="text/javascript" src="./js/datepickr.js"></script>-->
<!-- Date picker plugin http://dhtmlx.com/docs/products/dhtmlxCalendar/--->
<link rel="stylesheet" type="text/css" href="./plugins/datepicker/dhtmlxcalendar.css">
      <link rel="stylesheet" type="text/css" href="./plugins/datepicker/skins/dhtmlxcalendar_dhx_skyblue.css">
      <script src="./plugins/datepicker/dhtmlxcalendar.js"></script>
<!--loading validation jquery-->
<script src="./js/jquery.validate.js" type="text/javascript"></script>
<!-- check if user is idle and do actions http://www.paulirish.com/2009/jquery-idletimer-plugin/ -->

<script type="text/javascript" src="./js/homeJS.js"></script>
<!--loading datepicker javascript not jquery-->
<script type="text/javascript" src="./js/setup.js"></script>



