<div class="mainmenu">
<div id='cssmenu'>
<ul>
   <li id="mnuhome" class='active'><a href='#home'><img src="images/icons/home.png" class="menuicon" alt=""><span>الرئيسية</span></a></li>
   <li id="mnuabout"><a href='#about'><img src="images/icons/about.png" class="menuicon" alt=""><span>من نحن</span></a></li>
 <!--  <li id="mnulog"><a href='#'><img src="images/icons/login.png" class="menuicon" alt=""><span>تسجيل الدخول</span></a></li>-->
   <!--<li id="mnureg"><a href='#registration'><img src="images/icons/sign-up.png" class="menuicon" alt=""><span>اشترك الآن</span></a></li>-->
   <li id="mnucontact"><a href='#contactus'><img src="images/icons/contactus.png" class="menuicon" alt=""><span>اتصل بنا</span></a></li>
   <!--<li class='last'><a href='index.html#home'><img src="images/icons/englan.png" class="menuicon" alt=""><span>تغيير اللغة</span></a></li>-->
<li id="mnulog"><a id="login_pop" href='#login_form'><img src="images/icons/login.png" class="menuicon" alt=""><span>تسجيل الدخول</span></a></li>

</ul>
</div>
</div>