<div class="mainslideshow">
<div class="slideshow">
      <div class="slide" id="slide1">
            
             <img src="images/slides/slide1.png">
      </div>
      <div class="slide" id="slide2">
            
            <img src="images/slides/slide2.png">
      </div>
      <div class="slide" id="slide3">
            
            <img src="images/slides/slide3.png">
      </div>
      <div class="slide" id="slide4">
            
            <img src="images/slides/slide4.png">
      </div>
 </div>

</div>